### ISSUE TITLE
PlatformNotReady

### ISSUE THREAD

**Issue by holdestmade** [danieldotnl/hass-multiscrape#3]
Not sure why, maybe because its scraping every 30 seconds and the website has refused it ?

```
Logger: custom_components.multiscrape.sensor
Source: custom_components/multiscrape/sensor.py:185
Integration: multiscrape
First occurred: 9:09:50 (1 occurrences)
Last logged: 9:09:50

Unexpected error fetching multiscrape data:
Traceback (most recent call last):
  File "/config/custom_components/multiscrape/sensor.py", line 174, in async_update_data
    async with session.request(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/multiscrape/sensor.py", line 183, in async_update_data
    return select_values(result)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 143, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 131, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multiscrape/sensor.py", line 185, in async_update_data
    raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady
```

**Comment by danieldotnl** [comment]
Yes, the request to your API gave a timeout on startup of Home Assistant. This causes the PlatformNotReady exception. HA will then keep retrying for some time.
